package me.quadphase.qpdex;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : QPdex (C) 2015
//  @ File Name : Ability.java
//  @ Date : 21-Jul-15
//  @ Author : Nicole
//
//




/** */
public class Ability {
	/** Name of the ability */
	private String name;
	
	/** What the ability can do */
	private String description;

    /** Constructor */
    public Ability(String name, String description) {
        this.name = name;
        this.description = description;
    }

    public String getName() {
		return name;
	}

	public String getDescription() {
		return description;
	}
}
