package me.quadphase.qpdex;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : QPdex (C) 2015
//  @ File Name : Game.java
//  @ Date : 21-Jul-15
//  @ Author : Nicole
//
//


/** */
public class Game {
    /**
     * name of the game
     */
    private String name;

    /**
     * Generation that the game belongs to
     */
    private int generation;

    /**
     * Constructor
     */
    public Game(String name, int generation) {
        this.name = name;
        this.generation = generation;
    }

    /**
     * Getters
     */
    public String getName() {
        return name;
    }

    public int getGeneration() {
        return generation;
    }
}
