package me.quadphase.qpdex;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : QPdex (C) 2015
//  @ File Name : Move.java
//  @ Date : 21-Jul-15
//  @ Author : Nicole
//
//


/** */
public class Move {

    /**
     * name of the move
     */
    private String name;

    /**
     * what the move can do
     */
    private String description;

    /**
     * the power of the move
     */
    private int power;

    /**
     * the percentage accuracy of the move
     */
    private int accuracy;

    /**
     * the pp of the move
     */
    private int pp;

    /**
     * who this move affects
     */
    private String affects;

    /**
     * the generation that this move appears in
     */
    private int genFirstAppeared;

    /**
     * the secondary effects of the move
     */
    private String secondaryEffects;

    /**
     * the category of the move
     * Possible categories:
     * - Special
     * - Status
     * - Physical
     */
    private String category;

    /**
     * the type of the move
     */
    private Type type;

    /**
     * Constructor
     */
    public Move(String name, String description, int power, int accuracy, int pp, String affects, int genFirstAppeared, String secondaryEffects, String category, Type type) {
        this.name = name;
        this.description = description;
        this.power = power;
        this.accuracy = accuracy;
        this.pp = pp;
        this.affects = affects;
        this.genFirstAppeared = genFirstAppeared;
        this.secondaryEffects = secondaryEffects;
        this.category = category;
        this.type = type;
    }

    /**
     * Getters
     */
    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public int getPower() {
        return power;
    }

    public int getAccuracy() {
        return accuracy;
    }

    public int getPp() {
        return pp;
    }

    public String getAffects() {
        return affects;
    }

    public int getGenFirstAppeared() {
        return genFirstAppeared;
    }

    public String getSecondaryEffects() {
        return secondaryEffects;
    }

    public String getCategory() {
        return category;
    }

    public Type getType() {
        return type;
    }
}
