package me.quadphase.qpdex.pokemon;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : QPdex (C) 2015
//  @ File Name : Ability.java
//  @ Date : 21-Jul-15
//  @ Author : Nicole
//
//


/** */
public class Ability {
    /**
     * Name of the ability
     */
    private String name;

    /**
     * What the ability can do
     */
    private String description;

    /**
     * Constructor
     */
    public Ability(String name, String description) {
        this.name = name;
        this.description = description;
    }

    /**
     * Getters
     */
    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    /**
     * Overide for advanced search to display the id and name of type
     *
     * @return id. TypeName in string format
     */
    @Override
    public String toString(){
        return String.format("%s",name);
    }
}
