package me.quadphase.qpdex.pokemon;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : QPdex (C) 2015
//  @ File Name : EggGroup.java
//  @ Date : 21-Jul-15
//  @ Author : Nicole
//
//


/**
 * will be used to determine breeding potential of the Pokemon
 */
public class EggGroup {
    /**
     * Name of the egg group
     * Can be:
     * - monster
     * - water 1
     * - water 2
     * - water 3
     * - human-like
     * - bug
     * - mineral
     * - flying
     * - amorphous
     * - field
     * - fairy
     * - ditto
     * - grass
     * - dragon
     * - undiscovered
     * - gender unknown
     */
    private String name;

    /**
     * Constructor
     */
    public EggGroup(String name) {
        this.name = name;
    }

    /**
     * Getter
     */
    public String getName() {
        return name;
    }

    /**
     * Overide for advanced search to display the id and name of type
     *
     * @return id. TypeName in string format
     */
    @Override
    public String toString(){
        return name;
    }
}
