package me.quadphase.qpdex.pokemon;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : QPdex (C) 2015
//  @ File Name : Location.java
//  @ Date : 21-Jul-15
//  @ Author : Nicole
//
//


/** */
public class Location {
    /**
     * name of the location
     */
    private String name;

    /**
     * game that the location is found in
     */
    private Game game;

    /**
     * Constructor
     */
    public Location(String name, Game game) {
        this.name = name;
        this.game = game;
    }

    /**
     * Getters
     */
    public String getName() {
        return name;
    }

    public Game getGame() {
        return game;
    }
}
