package me.quadphase.qpdex.pokemon;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : QPdex (C) 2015
//  @ File Name : Type.java
//  @ Date : 21-Jul-15
//  @ Author : Nicole
//
//


/** */
public class Type {
    /**
     * name of the type
     * can be either:
     * - normal
     * - fighting
     * - flying
     * - poison
     * - poison
     * - ground
     * - rock
     * - bug
     * - ghost
     * - steel
     * - fire
     * - water
     * - grass
     * - electric
     * - psychic
     * - ice
     * - dragon
     * - dark
     * - fairy
     * - ???
     */
    private String name;

    /**
     * Constructor
     */
    public Type(String name) {
        this.name = name;
    }

    /**
     * Getters
     */
    public String getName() {
        return name;
    }

}
