package me.quadphase.qpdex.pokemon;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : QPdex (C) 2015
//  @ File Name : Type.java
//  @ Date : 21-Jul-15
//  @ Author : Nicole
//
//


import me.quadphase.qpdex.databaseAccess.PokemonFactory;

/** */
public class Type {
    /**
     * name of the type
     * can be either:
     * - normal
     * - fighting
     * - flying
     * - poison
     * - poison
     * - ground
     * - rock
     * - bug
     * - ghost
     * - steel
     * - fire
     * - water
     * - grass
     * - electric
     * - psychic
     * - ice
     * - dragon
     * - dark
     * - fairy
     * - ???
     */
    private String name;

    /**
     * Constructor
     */
    public Type(String name) {
        this.name = name;
    }

    /**
     * Getters
     */
    public String getName() {
        return name;
    }

    /**
     * Determine the attacking effectiveness of this type against a defending one.
     *
     * @param defendingType type that this type is defending against
     * @return the attacking effectiveness against the defendingType
     */
//    public short getAttackingEffectivenessAgainst (Type defendingType) {
//        PokemonFactory pokemonFactory = PokemonFactory.getPokemonFactory(null);
//        return pokemonFactory.getTypeEffectivenessTable()[pokemonFactory.getTypeID(this)][pokemonFactory.getTypeID(defendingType)];
//    }

    /**
     * Determine the defending effectiveness of this type against an attacking one.
     *
     * @param attackingType type that this type is attacking
     * @return the defensive effectiveness against the attackingType
     */
//    public short getDefendingEffectivenessAgainst (Type attackingType) {
//        PokemonFactory pokemonFactory = PokemonFactory.getPokemonFactory(null);
//        return pokemonFactory.getTypeEffectivenessTable()[pokemonFactory.getTypeID(attackingType)][pokemonFactory.getTypeID(this)];
//    }
}
